kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: sarahgreywolf/wasm-pack:1
  commands:
  - wasm-pack build --target web

- name: post
  image: plugins/webhook
  settings: 
    username:
      from_secret: discord_webhook_id
    password:
      from_secret: discord_webhook_token
    urls:
      from_secret: discord_webhook_url
    content_type: application/json
    template: |
      {
        "username": "Drone {{repo.name}}",
        "content": "
        {{#success build.status}}
          Build {{build.number}}, started at {{build.started}} succeeded!
          Taking {{since build.started}}.
        {{else}}
          build {{build.number}} failed!
        {{/success}}"
      }
